### ISSUE TITLE
Data corruption: zeroes are sometimes written instead of the actual data

### ISSUE THREAD

**Issue by abbradar** [juicedata/juicefs#5038]
**What happened**:
When writing a file on a host, sometimes a zero-filled region may be written instead of the actual data.

**What you expected to happen**:
No data corruption.

**How to reproduce it (as minimally and precisely as possible)**:

On one host: `pv -L 3k /dev/urandom > /mnt/shfe-partition/test-file`
On another host: `while ! hexdump -C /mnt/shfe-partition/test-file | grep '00 00 00 00'; do sleep 1; done`

After some time, the command on the second host will find a large cluster of zeroes (>1k) and stop. In the file, you see, for instance:

```
00033130  26 32 91 00 00 00 00 00  00 00 00 00 00 00 00 00  |&2..............|
00033140  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00036000  88 ff a0 0b c6 17 26 95  78 b7 e3 28 f5 35 8b 98  |......&.x..(.5..|
```

**Anything else we need to know?**

More details:
* The network on the *writing* host is quite overloaded/unstable; I believe this may be related because the issue only occurs when the network is overloaded. No other (hardware, disk) failures are observed on the host;
* The zero byte clusters are often, *but not always*, have 1k-divisible size;
* EIO errors sometimes happen on the writing side (because of the bad networking), but they don't seem to correlate to the issues directly;
* Zero clusters appear in the middle of the file, not at the beginning or end;
* Compression and encryption are enabled.

Unfortunately, we have many irrelevant logs on the *writing* server because this is a production host. These ones may be relevant (the file inode is 2439005):
```
2024/07/30 07:53:45.891705 juicefs[4019926] <ERROR>: write inode:2439005 indx:0  input/output error [writer.go:211]
2024/07/30 07:53:52.457389 juicefs[4019926] <WARNING>: slow request: PUT chunks/20/20750/20750481_3_4194304 (req_id: "", err: Put "https://somehost/somedb/%2Fchunks%2F20%2F20750%2F20750481_3_4194304": write tcp 10.42.43.15:60050->100.118.102.36:443: use of closed network connection, cost: 59.994437087s) [cached_store.go:667]
[mysql] 2024/07/30 07:54:35 packets.go:37: read tcp 10.42.43.15:47762->10.0.8.236:3306: read: connection reset by peer
2024/07/30 07:54:35.379260 juicefs[4019926] <WARNING>: Upload chunks/20/20750/20750498_5_4194304: timeout after 1m0s: function timeout (try 1) [cached_store.go:407]
2024/07/30 07:54:39.800111 juicefs[4019926] <INFO>: slow operation: flush (2439005,17488,6D9AF143D1C50E5B) - input/output error <53.869292> [accesslog.go:83]
```

What else do we plan to try:
* Writing from different hosts with similar networking to completely figure out hardware issues;
* Checking the metadata to see if the zero clusters correspond to single chunks.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: `juicefs version 1.2.0+2024-06-18.873c47b922ba` (both hosts)
- Cloud provider or hardware configuration running JuiceFS: Bare-metal host on the writing side, Aliyun ECS on the reading side
- OS (e.g `cat /etc/os-release`): NixOS 24.11 (Vicuna) (both hosts)
- Kernel (e.g. `uname -a`): `6.1.90` (both hosts)
- Object storage (cloud provider and region, or self maintained): Aliyun OSS
- Metadata engine info (version, cloud provider managed or self maintained): Aliyun RDS, MySQL
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): Private Aliyun networking on the reading side, public Internet on the writing side
- Others:

**Comment by jiefenghuang** [comment]
It seems similar to one previous issue, it could be caused by concurrent chunk commit that lead to file length changes. Would it be normal reading again after a while?

**Comment by abbradar** [comment]
No, the file that was corrupted in this way stays the same. I just checked the one that I tested this on. The flow has been:
* Run the commands above;
* First, the reading one (`hexdump`) detects a zero region and stops;
* In a minute, the writing one (`pv`) crashes with EIO (but I think I saw instances of this bug happening without the writing side crashing);
* The written file is not touched for ~3 hours, and then (right now) I check if it still has the zero regions — it does.

**Comment by jiefenghuang** [comment]
JuiceFS provides close-to-open consistency, once a file is written and closed, it is guaranteed to view the written data in the following opens and reads from any client.

If one client is writing while another client is reading simultaneously, inconsistencies may occur. Additionally, if the client  write failed due to object storage issues, the behavior at the point of write failure is undefined, the file may contain zero region.

**Comment by abbradar** [comment]
> Additionally, if the client write failed due to object storage issues, the behavior at the point of write failure is undefined, the file may contain zero region.

Do you mean that if the object storage itself exhibits this behavior and may leave corrupted zero-filled objects, then this propagates to the FS level? I would have expected the region to be random garbage or for a read error to happen then because we use JuiceFS encryption on top; please correct me if I'm wrong.

BTW, does JuiceFS use the `Content-MD5` header during uploads for S3-compatible storage?

**Comment by abbradar** [comment]
@jiefenghuang I just managed to reproduce the other behavior you mentioned. The setup was the same (one writing and another reading host), but I wrote a small script for the writing side to detect zero regions:

```python
import time
import sys

pat = b"\0"

pos = 0
while True:
    chunk = f.read(2048)
    if len(chunk) == 0:
        time.sleep(1)
    elif chunk.count(pat) == len(chunk):
        print(f"Pos {pos}: Zeroes chunk detected! Size: {len(chunk)}", flush=True)
    pos += len(chunk)
```

On the writing side, I ran `pv -L 3k /dev/urandom > /mnt/jfs-partition/test-file` again. I also ran `juicefs info /mnt/jfs-partition/test-file` in a loop at the reading side. Eventually I got:

```
Pos 38912: Zeroes chunk detected! Size: 2048
Pos 40960: Zeroes chunk detected! Size: 2048
Pos 43008: Zeroes chunk detected! Size: 2048
Pos 45056: Zeroes chunk detected! Size: 2048
Pos 47104: Zeroes chunk detected! Size: 2048                                                                                                          
Pos 49152: Zeroes chunk detected! Size: 2048
Pos 51200: Zeroes chunk detected! Size: 1331
```

And:
```
/mnt/jfs-partition/test-file :
  inode: 2439006
  files: 1
   dirs: 0
 length: 51.30 KiB (52531 Bytes)
   size: 52.00 KiB (53248 Bytes)
   path: /test-file
 objects:
+------------+--------------------------------------------+-------+--------+--------+
| chunkIndex |                 objectName                 |  size | offset | length |
+------------+--------------------------------------------+-------+--------+--------+
|          0 | jfs-partition/chunks/20/20038/20038936_0_21196 | 21196 |      0 |  21196 |
|          0 | jfs-partition/chunks/20/20834/20834060_0_15668 | 15668 |      0 |  15668 |
|          0 | jfs-partition/chunks/20/20834/20834062_0_15667 | 15667 |      0 |  15667 |
+------------+--------------------------------------------+-------+--------+--------+
```

Notice that zeroes begin at the chunk border (21196 + 15668 == 38912), and indeed, stretch the entire chunk.

Can you point me to the known issue?

**Comment by jiefenghuang** [comment]
> @jiefenghuang I just managed to reproduce the other behavior you mentioned. The setup was the same (one writing and another reading host), but I wrote a small script for the reading side to detect zero regions:
> 
> ```python
> import time
> import sys
> 
> pat = b"\0"
> 
> f = open("/mnt/jfs-partition/test-file", "rb")
> pos = 0
> while True:
>     chunk = f.read(2048)
>     if len(chunk) == 0:
>         time.sleep(1)
>     elif chunk.count(pat) == len(chunk):
>         print(f"Pos {pos}: Zeroes chunk detected! Size: {len(chunk)}", flush=True)
>     pos += len(chunk)
> ```
> 
> On the writing side, I ran `pv -L 3k /dev/urandom > /mnt/jfs-partition/test-file` again. I also ran `juicefs info /mnt/jfs-partition/test-file` in a loop at the reading side. Eventually I got:
> 
> ```
> Pos 38912: Zeroes chunk detected! Size: 2048
> Pos 40960: Zeroes chunk detected! Size: 2048
> Pos 43008: Zeroes chunk detected! Size: 2048
> Pos 45056: Zeroes chunk detected! Size: 2048
> Pos 47104: Zeroes chunk detected! Size: 2048                                                                                                          
> Pos 49152: Zeroes chunk detected! Size: 2048
> Pos 51200: Zeroes chunk detected! Size: 1331
> ```
> 
> And:
> 
> ```
> /mnt/jfs-partition/test-file :
>   inode: 2439006
>   files: 1
>    dirs: 0
>  length: 51.30 KiB (52531 Bytes)
>    size: 52.00 KiB (53248 Bytes)
>    path: /test-file
>  objects:
> +------------+--------------------------------------------+-------+--------+--------+
> | chunkIndex |                 objectName                 |  size | offset | length |
> +------------+--------------------------------------------+-------+--------+--------+
> |          0 | jfs-partition/chunks/20/20038/20038936_0_21196 | 21196 |      0 |  21196 |
> |          0 | jfs-partition/chunks/20/20834/20834060_0_15668 | 15668 |      0 |  15668 |
> |          0 | jfs-partition/chunks/20/20834/20834062_0_15667 | 15667 |      0 |  15667 |
> +------------+--------------------------------------------+-------+--------+--------+
> ```
> 
> Notice that zeroes begin at the chunk border (21196 + 15668 == 38912), and indeed, stretch the entire chunk.
> 
> But when I reopened the file later, no zero regions were there!
> 
> Can you point me to the known issue?

It is a question asked by a user in a WeCom user group, and has not been posted on GitHub Issue.

> @abbradar This is not a bug. JuiceFS provides close-to-open consistency, once a file is written and closed, it is guaranteed to view the written data in the following opens and reads from any client.
> 
> 1. If one client is writing while another client is reading simultaneously, inconsistencies may occur. You should expect to obtain valid data through "read-after-flush", not "read-after-write".
> 2. If the client write failed due to object storage (or other) issues, this part of file is meaningless. You should not expect to read valid data from it.

I've made some modifications, it may have resolved your question.

**Comment by abbradar** [comment]
@jiefenghuang Thanks; I have several questions about these.

For (1), with no write failures, does this property mean:
* Parts of the file are not synchronized (e.g., the order of random writes is not preserved, and writes are not guaranteed to be visible) before `close()`;
* Or the reader might read completely invalid data?
We use JuiceFS for writing append-only binary logs, and read them sequentially on another host in real time. We are not concerned with not having a time guarantee, but the possibility of reading invalid data breaks this pattern.

(2) is a problem for us. I would have expected JuiceFS to behave like a checksummed+journaled file system here—i.e., exclude the possibility of corrupted data, so the worst case becomes either "reading gives you EIO" or "write happened partially/did not happen". Can you clarify a bit more on how this works internally — what sequence of metadata+object operations can result in reading zero chunks, and what happens later when they get magically fixed?

**Comment by davies** [comment]
We could improve this case in next 1.3 release

**Comment by abbradar** [comment]
Thanks! We have lots of use cases for "one host appends, another reads", so we are motivated to help with this.

**Comment by abbradar** [comment]
We have caught a much more alarming instance of maybe the same bug. I'll describe it here first, but move it if you think it's appropriate. Because the setup is complicated, there might be something we overlooked, so I'll explain it in detail.

The full setup:
* MySQL+Alibaba OSS JuiceFS with encryption and compression;
* Two hosts, A and B. Both running 1.2.1;
* Host A has these JuiceFS settings: `attr-cache=1,entry-cache=1,dir-entry-cache=1,open-cache=1`;
* Host B has the same + `no-bgjob`.

Next, host B has:
* A daemon that writes a text log file sequentially *on a local disk*, ext4 fs. It uses simple `open`/`write`/`close`, no seeks, and doesn't overwrite the file;
* A background script:
```
while true; do
  rsync -rav --inplace --no-whole-file ./local/log-files /juicefs/log-files
  sleep 5
done
```

So, the JuiceFS file is periodically opened on the host B, updated by rsync to match the growing local log file, and closed.

Host A periodically reads `/juicefs/log-files`, otherwise it doesn't interact with anything.

After one of the log files was rotated a week ago, we found it to be corrupted on JuiceFS. The local file has not yet been removed, so we can compare them:

* The files have completely identical metadata, so `rsync` was fooled into thinking no difference between files exists and didn't check the contents;
* The JuiceFS copy of the file has a region of zeroes of size 1323817 in the end, very similar to what we observed here.
* The corrupted file can be read from JuiceFS on both hosts A and B, even with the caches cleared.

My current theory is that this 1323817 zero chunk got written instead of the actual data when rsync updated the file one final time after it was rotated.

Do you agree this might indicate a JuiceFS issue? What can I do to help you investigate?

**Comment by kitobelix** [comment]
I think I have the same issue. I'm starting to see this in one of my infras with configuration files (text like yaml and json) where in one host they are updated and others see the same file updated but with a stripped eof with some zeroes, but surprisingly the same lenght as before the update on the other host.

**Comment by davies** [comment]
@abbradar We fixed a issue (#6192) which could be related to this one, can you test again latest main branch?

**Comment by YunhuiChen** [comment]
Use this script:
```
# -*- coding: utf-8 -*-
import time
import os
import random
import string
import sys
from threading import Thread

def random_string(size):
    return ''.join(random.choices(string.ascii_letters + string.digits, k=size))

def writer(filepath, duration_minutes=5):
    start_time = time.time()
    end_time = start_time + duration_minutes * 60

    while time.time() < end_time:
        # Generate random size between 1MB and 128MB (adjust range as needed)
        min_size = 1 * 1024 * 1024  # 1MB
        max_size = 128 * 1024 * 1024  # 128MB
        random_size = random.randint(min_size, max_size)

        data = random_string(random_size).encode('utf-8')

        with open(filepath, 'ab') as f:
            f.write(data)

        # Optional: print the size written
        print(f"[Writer] Written {random_size} bytes ({(random_size/1024/1024):.2f} MB)")

    print(f"[Writer] Test duration ({duration_minutes} minutes) completed, stopping writer.")

def watch_file(path1="/juicefs1/tmp.txt", path2="/juicefs2/tmp.txt", interval=0.01, duration_minutes=5):
    """
    Detect the change in file length every interval second (default 0.01 seconds, that is, 10ms).
    If there is any new content, read the new part and compare whether the corresponding parts of the two files are consistent.
    """
    start_time = time.time()
    end_time = start_time + duration_minutes * 60

    try:
        with open(path2, "rb") as f2:
            f2.seek(0, 2)
            last_pos = f2.tell()
    except FileNotFoundError:
        print(f"[Watcher] {path2} no exist，create it...")
        last_pos = 0

    with open(path2, "rb") as f2:
        while time.time() < end_time:
            time.sleep(interval)
            try:
                os.listdir('/juicefs2')
                f2.seek(0, 2)
                curr_size = f2.tell()

                if curr_size > last_pos:
                    f2.seek(last_pos)
                    data2 = f2.read(curr_size - last_pos)
                    last_pos = curr_size

                    try:
                        with open(path1, "rb") as f1:
                            f1.seek(last_pos - len(data2))
                            data1 = f1.read(len(data2))

                            if data1 != data2:
                                print(f"[Watcher] The differences are found in location {last_pos - len(data2)}-{last_pos}:")
                                diff_file1 = f"data1"
                                diff_file2 = f"data2"

                                with open(diff_file1, "wb") as df1:
                                    df1.write(data1)
                                with open(diff_file2, "wb") as df2:
                                    df2.write(data2)
                                print(f"[Watcher] The differences write to：{diff_file1} 和 {diff_file2}")
                                sys.exit(1)
                            else:
                                print(f"[Watcher] The newly added content is consistent. ({last_pos - len(data2)}-{last_pos})")
                    except FileNotFoundError:
                        print(f"[Watcher] file {path1} not exist")
                        continue

            except FileNotFoundError:
                last_pos = 0
                continue

    print(f"[Watcher] Test duration ({duration_minutes} minutes) completed, no differences found.")

def main():
    test_duration_minutes = 5
    filepath1 = '/juicefs1/tmp.txt'
    filepath2 = '/juicefs2/tmp.txt'

    for path in [filepath1, filepath2]:
        try:
            with open(path, 'wb') as f:
                f.write(b'')
        except IOError as e:
            sys.exit(1)

    writer_thread = Thread(target=writer, args=(filepath1, test_duration_minutes))
    writer_thread.daemon = True
    writer_thread.start()

    watch_file(filepath1, filepath2, duration_minutes=test_duration_minutes)

    writer_thread.join()

    print("test finally")

if __name__ == '__main__':
    main()
```
This problem can be reproduced 。
The same problem still exists after issue (https://github.com/juicedata/juicefs/pull/6192) was fixed， It should be two problems

**Comment by abbradar** [comment]
The problem can still be reproduced. My test setup is this script to detect zero regions in a file:

```
#!/usr/bin/env python

import time                                                                                                                                                                               
import sys
from datetime import datetime

def now():
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]

CHUNK_SIZE = 2048

def find_zero_start(chunk):
    """Find offset where trailing zeroes begin in a chunk."""
    for i in range(len(chunk) - 1, -1, -1):
        if chunk[i] != 0:
            return i + 1
    return 0

def find_zero_end(chunk):
    """Find offset where leading zeroes end in a chunk."""
    for i in range(len(chunk)):
        if chunk[i] != 0:
            return i
    return len(chunk)

f = open(sys.argv[1], "rb")
pos = 0
prev_chunk = None
in_zeroes = False
while True:
    chunk = f.read(CHUNK_SIZE)
    if len(chunk) == 0:
        time.sleep(1)
        continue
    all_zeroes = chunk.count(b"\0") == len(chunk)
    if all_zeroes and not in_zeroes:
        # Entering a zero region — check where zeroes actually start in prev chunk
        if prev_chunk is not None:
            zero_start = find_zero_start(prev_chunk)
            start_pos = pos - len(prev_chunk) + zero_start
        else:
            start_pos = pos
        print(f"{now()}, pos {start_pos}: Zero region starts", flush=True)
        in_zeroes = True
    elif not all_zeroes and in_zeroes:
        # Leaving a zero region — find where zeroes end in this chunk
        zero_end = find_zero_end(chunk)
        end_pos = pos + zero_end
        print(f"{now()}, pos {end_pos}: Zero region ends", flush=True)
        in_zeroes = False
    prev_chunk = chunk
    pos += len(chunk)
```

Then, on one host:
```
$ pv -L 3k /dev/urandom >> /mnt/jfs/corruption-test
```

And on another, I run the detection script and simultaneously `juicefs info` in a loop to find out what exactly happens.

An example of the issue found:
```
2026-04-13 11:54:11.162, pos 33796608: Zero region starts                         
2026-04-13 11:54:11.162, pos 33800192: Zero region ends
```

So the zeroed region length is 3584 bytes, it does *not* correspond to a block size this time. I'm pretty sure it's related the last block handling somehow, logs from `juicefs info`:
```
2026-04-13 11:54:10.219125
/mnt/jfs/corruption-test :
  inode: 2167551
  files: 1
   dirs: 0
 length: 32.23 MiB (33796608 Bytes)
   size: 32.23 MiB (33800192 Bytes)
   path: /corruption-test
 objects:
+------------+-------------------------------------------+---------+--------+---------+----------+
| chunkIndex |                objectName                 |   size  | offset |  length |    pos   |
+------------+-------------------------------------------+---------+--------+---------+----------+
|          0 | jfs/chunks/467/467441/467441795_0_4194304 | 4194304 |      0 | 4194304 |        0 |
|          0 | jfs/chunks/467/467441/467441795_1_4194304 | 4194304 |      0 | 4194304 |  4194304 |
|          0 | jfs/chunks/467/467441/467441795_2_4194304 | 4194304 |      0 | 4194304 |  8388608 |
|          0 | jfs/chunks/467/467441/467441795_3_4194304 | 4194304 |      0 | 4194304 | 12582912 |
|          0 | jfs/chunks/467/467441/467441795_4_4194304 | 4194304 |      0 | 4194304 | 16777216 |
|          0 | jfs/chunks/467/467441/467441795_5_4194304 | 4194304 |      0 | 4194304 | 20971520 |
|          0 | jfs/chunks/467/467441/467441795_6_1999872 | 1999872 |      0 | 1999872 | 25165824 |
|          0 | jfs/chunks/467/467442/467442296_0_4194304 | 4194304 |      0 | 4194304 | 27165696 |
|          0 | jfs/chunks/467/467442/467442296_1_1072025 | 1072025 |      0 | 1072025 | 31360000 |
|          0 | jfs/chunks/467/467442/467442494_0_1050317 | 1050317 |      0 | 1050317 | 32432025 |
|          0 | jfs/chunks/467/467442/467442582_0_312422  |  312422 |      0 |  312422 | 33482342 |
|          0 | jfs/chunks/468/468675/468675521_0_1844    |    1844 |      0 |    1844 | 33794764 |
+------------+-------------------------------------------+---------+--------+---------+----------+
2026-04-13 11:54:11.077325
/mnt/jfs/corruption-test :
  inode: 2167551
  files: 1
   dirs: 0
 length: 32.23 MiB (33800601 Bytes)
   size: 32.24 MiB (33804288 Bytes)
   path: /corruption-test
 objects:
+------------+-------------------------------------------+---------+--------+---------+----------+
| chunkIndex |                objectName                 |   size  | offset |  length |    pos   |
+------------+-------------------------------------------+---------+--------+---------+----------+
|          0 | jfs/chunks/467/467441/467441795_0_4194304 | 4194304 |      0 | 4194304 |        0 |
|          0 | jfs/chunks/467/467441/467441795_1_4194304 | 4194304 |      0 | 4194304 |  4194304 |
|          0 | jfs/chunks/467/467441/467441795_2_4194304 | 4194304 |      0 | 4194304 |  8388608 |
|          0 | jfs/chunks/467/467441/467441795_3_4194304 | 4194304 |      0 | 4194304 | 12582912 |
|          0 | jfs/chunks/467/467441/467441795_4_4194304 | 4194304 |      0 | 4194304 | 16777216 |
|          0 | jfs/chunks/467/467441/467441795_5_4194304 | 4194304 |      0 | 4194304 | 20971520 |
|          0 | jfs/chunks/467/467441/467441795_6_1999872 | 1999872 |      0 | 1999872 | 25165824 |
|          0 | jfs/chunks/467/467442/467442296_0_4194304 | 4194304 |      0 | 4194304 | 27165696 |
|          0 | jfs/chunks/467/467442/467442296_1_1072025 | 1072025 |      0 | 1072025 | 31360000 |
|          0 | jfs/chunks/467/467442/467442494_0_1050317 | 1050317 |      0 | 1050317 | 32432025 |
|          0 | jfs/chunks/467/467442/467442583_0_314266  |  314266 |      0 |  314266 | 33482342 |
|          0 | jfs/chunks/468/468675/468675523_0_1843    |    1843 |      0 |    1843 | 33796608 |
|          0 | jfs/chunks/468/468675/468675524_0_2150    |    2150 |      0 |    2150 | 33798451 |
+------------+-------------------------------------------+---------+--------+---------+----------+
2026-04-13 11:54:11.943784
/mnt/jfs/corruption-test :
  inode: 2167551
  files: 1
   dirs: 0
 length: 32.23 MiB (33800601 Bytes)
   size: 32.24 MiB (33804288 Bytes)
   path: /corruption-test
 objects:
+------------+-------------------------------------------+---------+--------+---------+----------+
| chunkIndex |                objectName                 |   size  | offset |  length |    pos   |
+------------+-------------------------------------------+---------+--------+---------+----------+
|          0 | jfs/chunks/467/467441/467441795_0_4194304 | 4194304 |      0 | 4194304 |        0 |
|          0 | jfs/chunks/467/467441/467441795_1_4194304 | 4194304 |      0 | 4194304 |  4194304 |
|          0 | jfs/chunks/467/467441/467441795_2_4194304 | 4194304 |      0 | 4194304 |  8388608 |
|          0 | jfs/chunks/467/467441/467441795_3_4194304 | 4194304 |      0 | 4194304 | 12582912 |
|          0 | jfs/chunks/467/467441/467441795_4_4194304 | 4194304 |      0 | 4194304 | 16777216 |
|          0 | jfs/chunks/467/467441/467441795_5_4194304 | 4194304 |      0 | 4194304 | 20971520 |
|          0 | jfs/chunks/467/467441/467441795_6_1999872 | 1999872 |      0 | 1999872 | 25165824 |
|          0 | jfs/chunks/467/467442/467442296_0_4194304 | 4194304 |      0 | 4194304 | 27165696 |
|          0 | jfs/chunks/467/467442/467442296_1_1072025 | 1072025 |      0 | 1072025 | 31360000 |
|          0 | jfs/chunks/467/467442/467442494_0_1050317 | 1050317 |      0 | 1050317 | 32432025 |
|          0 | jfs/chunks/467/467442/467442583_0_314266  |  314266 |      0 |  314266 | 33482342 |
|          0 | jfs/chunks/468/468675/468675523_0_1843    |    1843 |      0 |    1843 | 33796608 |
|          0 | jfs/chunks/468/468675/468675524_0_2150    |    2150 |      0 |    2150 | 33798451 |
+------------+-------------------------------------------+---------+--------+---------+----------+
2026-04-13 11:54:12.794785
/mnt/jfs/corruption-test :
  inode: 2167551
  files: 1
   dirs: 0
 length: 32.24 MiB (33806131 Bytes)
   size: 32.24 MiB (33808384 Bytes)
   path: /corruption-test
 objects:
+------------+-------------------------------------------+---------+--------+---------+----------+
| chunkIndex |                objectName                 |   size  | offset |  length |    pos   |
+------------+-------------------------------------------+---------+--------+---------+----------+
|          0 | jfs/chunks/467/467441/467441795_0_4194304 | 4194304 |      0 | 4194304 |        0 |
|          0 | jfs/chunks/467/467441/467441795_1_4194304 | 4194304 |      0 | 4194304 |  4194304 |
|          0 | jfs/chunks/467/467441/467441795_2_4194304 | 4194304 |      0 | 4194304 |  8388608 |
|          0 | jfs/chunks/467/467441/467441795_3_4194304 | 4194304 |      0 | 4194304 | 12582912 |
|          0 | jfs/chunks/467/467441/467441795_4_4194304 | 4194304 |      0 | 4194304 | 16777216 |
|          0 | jfs/chunks/467/467441/467441795_5_4194304 | 4194304 |      0 | 4194304 | 20971520 |
|          0 | jfs/chunks/467/467441/467441795_6_1999872 | 1999872 |      0 | 1999872 | 25165824 |
|          0 | jfs/chunks/467/467442/467442296_0_4194304 | 4194304 |      0 | 4194304 | 27165696 |
|          0 | jfs/chunks/467/467442/467442296_1_1072025 | 1072025 |      0 | 1072025 | 31360000 |
|          0 | jfs/chunks/467/467442/467442494_0_1050317 | 1050317 |      0 | 1050317 | 32432025 |
|          0 | jfs/chunks/468/468675/468675525_0_316109  |  316109 |      0 |  316109 | 33482342 |
|          0 | jfs/chunks/468/468675/468675524_0_2150    |    2150 |      0 |    2150 | 33798451 |
|          0 | jfs/chunks/468/468675/468675526_0_5530    |    5530 |      0 |    5530 | 33800601 |
+------------+-------------------------------------------+---------+--------+---------+----------+
```

Notice that:
* At some point, length equals the zero region start, size equals the zero region end;
* Then we get new blocks at the start of the zero region, but the sizes don't match.

Finally, checking the file after the fact doesn't show this corruption:
```
$ dd if=/mnt/jfs/corruption-test iseek=33796608 bs=1 count=2048 | hexdump -C
# ... (random garbage)
```

How else can I help to reproduce or debug this issue? It's still critical for us.

**Comment by polyrabbit** [comment]
@abbradar We have a similar use case internally and have hit the same issue. Strictly speaking, it’s not a bug: in JuiceFS, chunks written sequentially are still committed concurrently, so if the written file hasn’t been closed/flushed yet, readers may not see the latest data — this matches `close-to-open` expectation. However, while readers may temporarily not see the fresh data, they shouldn’t get empty holes either, that’s something JuiceFS can improve. Please try PR #6915 to see if it fixes your issue.
